driver

diff --git a/ecos b/ecos
--- a/ecos
+++ b/ecos
@@ -14,32 +14,23 @@ SCRIPT_TUI_FILE="$SCRIPT_DIR/.$SCRIPT_ID.tui"
 SCRIPT_TUI_WIDTH=68
 SCRIPT_TUI_HEIGHT=24
 
-# TERMINAL COLORS
-TERM_COLOR_RED='\033[0;31m'
-TERM_COLOR_GREEN='\033[1;32m'
-TERM_COLOR_BLUE='\033[1;34m'
-TERM_COLOR_PURPLE='\033[1;35m'
-TERM_COLOR_YELLOW='\033[1;33m'
-TERM_COLOR_NULL='\033[0m' # No Color
-
 # URLS
 ECOS_REPO_URL="https://github.com/murkl/ecos.git"
-ECOS_DOTS_DEFAULT_URL="https://github.com/murkl/dotfiles-gnome.git"
-ECOS_RAW_URL="https://raw.githubusercontent.com/murkl/ecos/main"
-ECOS_CORE_RELEASE_URL="$ECOS_RAW_URL/ecos"
+SCRIPT_FILE_URL="https://raw.githubusercontent.com/murkl/ecos/main/ecos"
+ECOS_DOTS_GNOME_URL="https://github.com/murkl/dotfiles-gnome.git"
+ECOS_DOTS_BSPWM_URL="https://github.com/murkl/dotfiles-bspwm.git"
 
 # ECOS HOME
 ECOS_HOME="$HOME/.ecos"
-ECOS_REPO="$ECOS_HOME/repo"
-ECOS_CORE="$ECOS_REPO/$SCRIPT_ID"
-ECOS_WORKING_DIR="$ECOS_HOME/.cache"
-ECOS_BIN_DIR="$HOME/.local/bin"
+ECOS_WORKING_DIR="$ECOS_HOME/.system"
+ECOS_REPO_DIR="$ECOS_WORKING_DIR/repo"
+ECOS_BIN_DIR="$ECOS_HOME/bin"
 ECOS_DOTFILES_DIR="$ECOS_WORKING_DIR/dotfiles"
 ECOS_INIT_SCRIPT="$ECOS_HOME/init.sh"
 
 # ECOS ASSETS
-ECOS_ICON_FILE="$ECOS_REPO/assets/ecos.svg"
-ECOS_CHANGELOG_FILE="$ECOS_REPO/assets/changelog.html"
+ECOS_ICON_FILE="$SCRIPT_DIR/assets/ecos.svg"
+ECOS_CHANGELOG_FILE="$SCRIPT_DIR/assets/changelog.html"
 ECOS_DESKTOP_FILE="$HOME/.local/share/applications/$SCRIPT_ID.desktop"
 ECOS_AUTOSTART_FILE="$HOME/.config/autostart/$SCRIPT_ID.desktop"
 
@@ -54,8 +45,15 @@ ECOS_STATE_SHOW_CHANGELOG="$ECOS_STATE_DIR/ecos_show_changelog"
 ECOS_STATE_LATEST_INIT="$ECOS_STATE_DIR/ecos_latest_init"
 
 # ECOS TWEAKS
-ECOS_TWEAKS_INSTALLED="$ECOS_WORKING_DIR/tweaks"
-ECOS_USER_TWEAKS_DIR="$ECOS_HOME/tweaks"
+ECOS_TWEAKS_DIR="$SCRIPT_DIR/tweaks"
+ECOS_TWEAKS_USER_DIR="$ECOS_HOME/tweaks"
+ECOS_TWEAKS_META_DIR="$ECOS_WORKING_DIR/tweaks-meta"
+
+# ECOS DRIVER
+ECOS_DRIVER_DIR="$SCRIPT_DIR/driver"
+ECOS_DRIVER_GRAPHICS_SCRIPT="$ECOS_DRIVER_DIR/graphics.sh"
+ECOS_DRIVER_AUDIO_SCRIPT="$ECOS_DRIVER_DIR/audio.sh"
+ECOS_DRIVER_META_DIR="$ECOS_WORKING_DIR/driver-meta"
 
 # ECOS UPDATE
 ECOS_REMOTE_VERSION_FILE='/tmp/ecos.remote'
@@ -64,11 +62,34 @@ ECOS_REMOTE_VERSION=''
 # ECOS DEFAULT PROPERTIES
 TERMINAL_EXEC='gnome-terminal -e'
 
+# TERMINAL COLORS
+TERM_COLOR_RED='\033[0;31m'
+TERM_COLOR_GREEN='\033[1;32m'
+TERM_COLOR_BLUE='\033[1;34m'
+TERM_COLOR_PURPLE='\033[1;35m'
+TERM_COLOR_YELLOW='\033[1;33m'
+TERM_COLOR_NULL='\033[0m' # No Color
+
 #/////////////////////////////////////////////////////
 # MAIN
 #/////////////////////////////////////////////////////
 
 main() {
+
+    # ---------------------------------------
+    # API
+    # ---------------------------------------
+    if [ "$1" = "--api" ]; then
+        if [ "$2" = "" ]; then
+            echo -e "\nUse ECOS API with action:\n\n"
+            echo -e "\tzenity <ARGS>"
+            exit 1
+        fi
+        local api_action="$2"
+        shift && shift || exit 1
+        ecos_api "$api_action" "$@"
+        exit 0
+    fi
 
     # ---------------------------------------
     # SHOW VERSION
@@ -145,6 +166,36 @@ main() {
     fi
 }
 
+ecos_api() {
+
+    local api_action="$1"
+    local api_arguments=()
+
+    if [ "$2" != "" ]; then
+        shift || exit 1
+        api_arguments=("$@")
+    fi
+
+    local api_arguments=("$@")
+    echo "API ARGUMENTS: ${api_arguments[@]}"
+    echo "API ARGUMENT COUNT: ${#api_arguments[@]}"
+
+    # echo -e "ECOS API ACTION: $api_action"
+    # echo "API ARGUMENTS: ${api_arguments[@]}"
+    # echo "API ARGUMENT COUNT: ${#api_arguments[@]}"
+
+    if [ "$api_action" = "zenity" ]; then
+
+        #api_zenity ${api_arguments[@]}
+        api_zenity "$@"
+        exit $?
+    fi
+}
+
+api_zenity() {
+    zenity --list --hide-header --column="" --text="$(print_zenity_header 'Menu' 'as')" --cancel-label='Exit' --ok-label='Ok' $@
+}
+
 #/////////////////////////////////////////////////////
 # ZENITY
 #/////////////////////////////////////////////////////
@@ -210,6 +261,7 @@ zenity_main_menu() {
     menu_entries+=("Update")
     menu_entries+=("Dotfiles")
     menu_entries+=("Tweaks")
+    menu_entries+=("Driver")
     menu_entries+=("Settings")
     if ! zenity_result="$(zenity --list --hide-header --column="" --text="$(print_zenity_header 'Menu' $ECOS_REMOTE_VERSION)" --cancel-label='Exit' --ok-label='Ok' "${menu_entries[@]}")"; then
         exit 0
@@ -225,8 +277,11 @@ zenity_main_menu() {
         exit 0
     fi
     if [ "$zenity_result" = "Tweaks" ]; then
-        update_ecos_repo
-        ${TERMINAL_EXEC} 'bash -c "'$ECOS_CORE' --install-tweaks"'
+        ${TERMINAL_EXEC} 'bash -c "'$SCRIPT_FILE' --install-tweaks"'
+        exit 0
+    fi
+    if [ "$zenity_result" = "Driver" ]; then
+        zenity_driver_menu
         exit 0
     fi
     if [ "$zenity_result" = "Settings" ]; then
@@ -276,6 +331,32 @@ zenity_settings() {
         notify "Settings saved"
     fi
 
+}
+
+zenity_driver_menu() {
+
+    check_git
+    check_paru
+
+    local menu_entries=()
+    menu_entries+=("Audio Driver")
+    menu_entries+=("Graphics Driver")
+    if ! zenity_result="$(zenity --list --hide-header --column="" --text="$(print_zenity_header 'Dotfiles' $ECOS_REMOTE_VERSION)" --cancel-label='Back' --ok-label='Ok' "${menu_entries[@]}")"; then
+        zenity_main_menu
+        return 0
+    fi
+
+    if [ "$zenity_result" = "Audio" ]; then
+        bash -c "$ECOS_DRIVER_AUDIO_SCRIPT" && wait
+        zenity_main_menu
+        return 0
+    fi
+
+    if [ "$zenity_result" = "Graphics Driver" ]; then
+        bash -c "$ECOS_DRIVER_GRAPHICS_SCRIPT" && wait
+        zenity_main_menu
+        return 0
+    fi
 }
 
 zenity_show_changelog() {
@@ -369,7 +450,7 @@ init_ecos() {
     mkdir -p "$ECOS_HOME"
     mkdir -p "$ECOS_BIN_DIR"
     mkdir -p "$ECOS_CONFIG_DIR"
-    mkdir -p "$ECOS_USER_TWEAKS_DIR"
+    mkdir -p "$ECOS_TWEAKS_USER_DIR"
     mkdir -p "$ECOS_WORKING_DIR"
     mkdir -p "$ECOS_STATE_DIR"
     mkdir -p "$HOME/.local/share/applications"
@@ -389,8 +470,8 @@ init_ecos() {
     if [ "$ECOS_REMOTE_VERSION" = '' ]; then
         local ecos_update="$ECOS_REMOTE_VERSION_FILE"
 
-        if ! curl -s -L "$ECOS_CORE_RELEASE_URL" >"$ECOS_REMOTE_VERSION_FILE"; then
-            echo "ERROR: DOWNLOAD ECOS: $ECOS_CORE_RELEASE_URL"
+        if ! curl -s -L "$SCRIPT_FILE_URL" >"$ECOS_REMOTE_VERSION_FILE"; then
+            echo "ERROR: DOWNLOAD ECOS: $SCRIPT_FILE_URL"
             return 1
         fi
         if ! chmod +x "$ECOS_REMOTE_VERSION_FILE"; then
@@ -424,11 +505,11 @@ tui_install_ecos() {
     if [ "$menu_input" = "1" ]; then
 
         tui_init 0 "Dotfiles URL"
-        if ! ECOS_DOTS_DEFAULT_URL=$(whiptail --inputbox "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" "$ECOS_DOTS_DEFAULT_URL" 3>&1 1>&2 2>&3); then
+        if ! ECOS_DOTS_GNOME_URL=$(whiptail --inputbox "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" "$ECOS_DOTS_GNOME_URL" 3>&1 1>&2 2>&3); then
             tui_install_ecos
             exit 0
         fi
-        if [ "$ECOS_DOTS_DEFAULT_URL" = "" ]; then
+        if [ "$ECOS_DOTS_GNOME_URL" = "" ]; then
             tui_init 0 "Dotfiles URL was empty!"
             whiptail --textbox "$SCRIPT_TUI_FILE" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH"
             tui_install_ecos
@@ -436,7 +517,7 @@ tui_install_ecos() {
         fi
 
         # Exec install
-        exec_install_ecos "$ECOS_DOTS_DEFAULT_URL"
+        exec_install_ecos "$ECOS_DOTS_GNOME_URL"
         exit 0
     fi
 
@@ -581,7 +662,7 @@ zenity_update_progress() {
     local LOG_FILE="/tmp/ecos_log_file"
     local STATE_FILE="/tmp/ecos_state_file"
 
-    ${TERMINAL_EXEC} 'bash -c "'$ECOS_CORE' --update"' &
+    ${TERMINAL_EXEC} 'bash -c "'$SCRIPT_FILE' --update"' &
     # Capture pid and show progress dialog
     local task_pid="$!"
     echo "$task_pid" >"$STATE_FILE"
@@ -601,27 +682,27 @@ update_ecos_repo() {
 
     cd "$HOME" || exit 1
 
-    if ! [ -d "$ECOS_REPO/.git" ]; then
+    if ! [ -d "$ECOS_REPO_DIR/.git" ]; then
         echo "CLONE ECOS REPO"
-        mkdir -p "$ECOS_REPO"
-        /usr/bin/git clone "$ECOS_REPO_URL" "$ECOS_REPO"
+        mkdir -p "$ECOS_REPO_DIR"
+        /usr/bin/git clone "$ECOS_REPO_URL" "$ECOS_REPO_DIR"
     fi
 
-    cd "$ECOS_REPO" || exit 1
+    cd "$ECOS_REPO_DIR" || exit 1
     /usr/bin/git fetch --all
     /usr/bin/git reset --hard origin/HEAD
     /usr/bin/git clean -d -f
     /usr/bin/git pull
 
     # Add user tweaks
-    if [ -d "$ECOS_USER_TWEAKS_DIR" ]; then
+    if [ -d "$ECOS_TWEAKS_USER_DIR" ]; then
 
-        readarray -d '' user_tweaks_list < <(find "$ECOS_USER_TWEAKS_DIR" -mindepth 1 -maxdepth 1 -type d -print0)
+        readarray -d '' user_tweaks_list < <(find "$ECOS_TWEAKS_USER_DIR" -mindepth 1 -maxdepth 1 -type d -print0)
 
         for i in "${user_tweaks_list[@]}"; do
 
             local tweak_id="$(basename $i)"
-            local tweak_sh="$ECOS_USER_TWEAKS_DIR/$tweak_id/${tweak_id}.sh"
+            local tweak_sh="$ECOS_TWEAKS_USER_DIR/$tweak_id/${tweak_id}.sh"
 
             # Check sh file
             if ! [ -f "$tweak_sh" ]; then
@@ -629,7 +710,7 @@ update_ecos_repo() {
             fi
 
             #Copy User tweaks
-            cp -r "$ECOS_USER_TWEAKS_DIR/$tweak_id" "$ECOS_REPO/tweaks/$tweak_id"
+            cp -r "$ECOS_TWEAKS_USER_DIR/$tweak_id" "$ECOS_DRIVER_DIR/$tweak_id"
         done
     fi
 }
@@ -752,13 +833,13 @@ tui_tweaks_menu() {
     #----------------------------------------
     # READ TWEAK LIST
     #----------------------------------------
-    readarray -d '' tweak_dir_list < <(find "$ECOS_REPO/tweaks" -mindepth 1 -maxdepth 1 -type d -print0)
+    readarray -d '' tweak_dir_list < <(find "$ECOS_TWEAKS_DIR" -mindepth 1 -maxdepth 1 -type d -print0)
 
     for i in "${tweak_dir_list[@]}"; do
 
         local tweak_id="$(basename $i)"
-        local tweak_sh="$ECOS_REPO/tweaks/$tweak_id/${tweak_id}.sh"
-        local tweak_meta="$ECOS_TWEAKS_INSTALLED/$tweak_id/${tweak_id}.tweak"
+        local tweak_sh="$ECOS_TWEAKS_DIR/$tweak_id/${tweak_id}.sh"
+        local tweak_meta="$ECOS_TWEAKS_META_DIR/$tweak_id/${tweak_id}.meta"
 
         # Check sh file
         if ! [ -f "$tweak_sh" ]; then
@@ -849,8 +930,8 @@ exec_tweak() {
 
     local tweak_action="$1"
     local tweak_id="$2"
-    local tweak_res_dir="$ECOS_REPO/tweaks/$tweak_id"
-    local tweak_cache_dir="$ECOS_TWEAKS_INSTALLED/$tweak_id"
+    local tweak_res_dir="$ECOS_TWEAKS_DIR/$tweak_id"
+    local tweak_cache_dir="$ECOS_TWEAKS_META_DIR/$tweak_id"
     local tweak_sh="$tweak_res_dir/${tweak_id}.sh"
     local tweak_meta="$tweak_cache_dir/${tweak_id}.tweak"
 
@@ -858,12 +939,12 @@ exec_tweak() {
     # Check
     #----------------------------------------
     if [ "$tweak_id" = "" ]; then
-        echo -e "Error: Tweak ID is empty.\nExecute with:\n$ECOS_CORE --tweak TWEAK_ACTION TWEAK_ID"
+        echo -e "Error: Tweak ID is empty.\nExecute with:\n$SCRIPT_FILE --tweak TWEAK_ACTION TWEAK_ID"
         exit 1
     fi
 
     if [ "$tweak_action" = "" ]; then
-        echo -e "Error: TWEAK_ACTION is empty.\nExecute with:\n$ECOS_CORE --tweak TWEAK_ACTION TWEAK_ID"
+        echo -e "Error: TWEAK_ACTION is empty.\nExecute with:\n$SCRIPT_FILE --tweak TWEAK_ACTION TWEAK_ID"
         exit 1
     fi
 
@@ -918,7 +999,7 @@ exec_tweak() {
 
 update_tweaks() {
     local tweak_dir_list=()
-    readarray -d '' tweak_dir_list < <(find "$ECOS_TWEAKS_INSTALLED" -mindepth 1 -maxdepth 1 -type d -print0)
+    readarray -d '' tweak_dir_list < <(find "$ECOS_TWEAKS_META_DIR" -mindepth 1 -maxdepth 1 -type d -print0)
 
     # Sort array
     IFS=$'\n' tweak_dir_list_sorted=($(sort <<<"${tweak_dir_list[*]}"))
@@ -926,7 +1007,7 @@ update_tweaks() {
 
     for i in "${tweak_dir_list_sorted[@]}"; do
         local tweak_id="$(basename $i)"
-        local tweak_sh="$ECOS_REPO/$tweak_id/${tweak_id}.sh"
+        local tweak_sh="$ECOS_REPO_DIR/$tweak_id/${tweak_id}.sh"
         exec_tweak "update" "$tweak_id"
     done
 }
