2.3.3
* dev version

* icons

* icon

* array

* array

* array

* colors

* state

* log

* states

* cleanup

* args

* cleanup

* ignore

* installer

* pids

* fix

* fix

* finished

Co-authored-by: moritz <moritz@moritz-desktop>

diff --git a/ecos b/ecos
--- a/ecos
+++ b/ecos
@@ -158,7 +158,7 @@ main() {
     # UPDATE NOTIFY
     # ---------------------------------------
     if [ "$1" = "--update-notify" ]; then
-        notify_ecos_update
+        update_ecos_remote && notify_ecos_update
         exit 0
     fi
 
@@ -166,7 +166,7 @@ main() {
     # ECOS AUTOSTART
     # ---------------------------------------
     if [ "$1" = "--autostart" ]; then
-        (sleep 10 && notify_ecos_update >/dev/null) &
+        (update_ecos_remote && sleep 5 && notify_ecos_update >/dev/null) &
         if [ "$ECOS_STATE_SHOW_CHANGELOG" = "true" ]; then
             zenity_show_changelog
         fi
@@ -193,7 +193,7 @@ main() {
     # OPEN MAIN MENU
     #----------------------------------------
     if [ "$1" = "" ]; then
-        zenity_main_menu
+        zenity_main_menu --init
         exit $?
     fi
 }
@@ -262,35 +262,24 @@ api_zenity_menu() {
 }
 
 api_zenity_progress() {
-    local title="$1"
-    shift || exit 1
-    local task_pid="$1"
-    local pid_file="/tmp/ecos.pids"
-
-    local api_arguments=("")
-    if [ "$2" != "" ]; then
-        shift || exit 1
-        api_arguments=("$@")
-    fi
+    local title="$1" && shift || exit 1
+    local task_pid="$1" && shift || exit 1
+    local task_status_file="$1" && shift || exit 1
+    local api_arguments=("$@")
 
     # Capture pid and show progress dialog
-    echo "$task_pid" >"$pid_file"
-    echo "TASK PID: $(cat $pid_file)"
-
     local txt_title='<span font_family="monospace" foreground="#494949" font="12"><b>'$title'</b></span>'
-    tail -f /dev/null --pid "$task_pid" | (zenity --progress --width=300 --height=150 --text="\n$txt_title\n" --pulsate --auto-close "${api_arguments[@]}" || (kill_pid "$task_pid" && echo "CANCELED" >"$pid_file"))
+    tail -f /dev/null --pid "$task_pid" | (zenity --progress --width=300 --height=150 --text="\n$txt_title\n" --pulsate --auto-close "${api_arguments[@]}" || (kill_pid "$task_pid" && echo "CANCELED" >"$task_status_file"))
 
     # Finish
-    local pid_state=$(<"$pid_file")
-    if [ "$pid_state" = "CANCELED" ]; then
-        echo "CANCELD"
-        exit 1
+    local task_status=$(<"$task_status_file")
+    rm -rf "$task_status_file"
+
+    if [ "$task_status" = "CANCELED" ]; then
+        echo "$task_status" && return 1
     fi
 
-    if [ "$pid_state" = "SUCCESS" ]; then
-        echo "SUCCESS"
-        exit 0
-    fi
+    echo "$task_status" && return 0
 }
 
 api_check_root_password() {
@@ -338,17 +327,9 @@ zenity_main_menu() {
             fi
         ) &
         local task_pid="$!"
+        local task_status=$(api_zenity_progress "Initialize $SCRIPT_TITLE CORE..." "$task_pid" "$task_status_file" --no-cancel)
 
-        # Capture pid and show progress dialog
-        echo "$task_pid" >"$pid_file"
-        local txt_title='<span font_family="monospace" foreground="#494949" font="12"><b>Initialize '$SCRIPT_TITLE' CORE...</b></span>'
-        tail -f /dev/null --pid $task_pid | (zenity --progress --width=300 --height=150 --no-cancel --text="\n\t$txt_title\n" --pulsate --auto-close || (kill_pid "$task_pid" && echo "CANCELED" >"$pid_file"))
-
-        # Finish
-        local pid_state=$(<"$pid_file")
-
-        if [ "$pid_state" = "CANCELED" ]; then
-            echo "INIT FAILED"
+        if [ "$task_status" = "CANCELED" ]; then
             return 1
         fi
 
@@ -781,20 +762,37 @@ zenity_update_progress() {
     local LOG_FILE="/tmp/ecos_log_file"
     local STATE_FILE="/tmp/ecos_state_file"
 
-    ${TERMINAL_EXEC} 'bash -c "'$SCRIPT_FILE' --update"' &
-    # Capture pid and show progress dialog
+    local task_status_file="/tmp/ecos-task.$(date "+%Y-%m-%d-%H:%M:%S")"
+    (${TERMINAL_EXEC} 'bash -c "'$SCRIPT_FILE' --update"' && wait) || echo "FAILED" >"$task_status_file" &
     local task_pid="$!"
-    echo "$task_pid" >"$STATE_FILE"
-    local txt_title='\t\t\t\t<span font_family="monospace" foreground="#494949" font="12"><b>'$SCRIPT_TITLE'</b></span>'
-    tail -f /dev/null --pid $task_pid | (zenity --progress --width=320 --height=180 --cancel-label="Cancel" --text="$txt_title\n\n\t\t\t\t <b>Update</b>\n" --pulsate --auto-close || (kill_pid "$task_pid" && echo "CANCELED" >"$STATE_FILE"))
+    local task_status=$(api_zenity_progress "Update $SCRIPT_TITLE..." "$task_pid" "$task_status_file" --no-cancel)
 
-    # Finish
-    local process_state=$(<"$STATE_FILE")
-
-    if [ "$process_state" = "CANCELED" ]; then
+    if [ "$task_status" = "CANCELED" ]; then
         notify "Update canceled"
         return 1
     fi
+    if [ "$task_status" = "FAILED" ]; then
+        notify "Update failed"
+        return 1
+    fi
+    if [ "$task_status" = "SUCCESS" ]; then
+        notify "Update sucessfull"
+    fi
+}
+
+update_ecos_remote() {
+    # DOWNLOAD REMOTE ECOS VERSION
+    if ! curl -s -L "$SCRIPT_FILE_URL" >"$ECOS_REMOTE_VERSION_FILE"; then
+        log -e "curl -s -L $SCRIPT_FILE_URL"
+        return 1
+    fi
+    if ! chmod +x "$ECOS_REMOTE_VERSION_FILE"; then
+        log -e "chmod +x $ECOS_REMOTE_VERSION_FILE"
+        return 1
+    fi
+
+    # SET VARS
+    wait && replace_config_value "$ECOS_STATE_FILE" "ECOS_STATE_VERSION_REMOTE" "$($ECOS_REMOTE_VERSION_FILE --version)"
 }
 
 update_ecos_remote() {
@@ -963,9 +961,7 @@ update_ecos_system() {
     update_tweaks
 
     # FINISH
-    echo -e "\n"
-    echo -e "${TERM_COLOR_GREEN}-------------------------------------------------${TERM_COLOR_NULL}"
-    echo -e "\n\n"
+    echo -e "\n\n\n\n"
     print_title "${TERM_COLOR_GREEN} !! ECOS UPDATE FINISHED !! ${TERM_COLOR_NULL}"
     echo -e "\n"
     read -p "Press any Key to close..."
