refactoring

diff --git a/ecos b/ecos
--- a/ecos
+++ b/ecos
@@ -1,30 +1,14 @@
 #!/bin/bash
-SCRIPT_VERSION=2.0.5
+SCRIPT_VERSION=2.0.6
 
 #/////////////////////////////////////////////////////
 # CHANGELOG
 #/////////////////////////////////////////////////////
 
 SCRIPT_CHANGELOG="
-2.0.5
-  + Tweaks
-  + Refactoring
-
-1.5.3
-  + Update mechanism refactored
-  + Fix: Plymouth Installation
-
-1.5.2
-  + Bugfixes
-  
-1.5.1
-  + New Manager + App Icon
-
-1.5.0
-  + New Update mechanism
-  + Sandbox Architecture (.ecos home dir)
-  + Binary: dots
-  + Refactoring
+$SCRIPT_VERSION
+  + New Tweaks Mechanism
+  + Big Refactoring
 "
 
 #/////////////////////////////////////////////////////
@@ -54,12 +38,12 @@ ECOS_ARCH_ISO_DEFAULT_URL="https://www.archlinux.de/download/iso/2021.11.01/arch
 ECOS_HOME="$HOME/.ecos"
 ECOS_BIN_DIR="$ECOS_HOME/bin"
 ECOS_CORE="$ECOS_BIN_DIR/$SCRIPT_ID"
-ECOS_CACHE="$ECOS_HOME/cache"
 ECOS_INIT="$ECOS_HOME/init"
-ECOS_INITIALIZED="$ECOS_CACHE/initialized"
 ECOS_LOCAL_DOTFILES="$ECOS_HOME/dotfiles"
-ECOS_TWEAKS_LOCAL_DIR="$ECOS_HOME/tweaks"
-ECOS_LOCAL_REPOS_DIR="$ECOS_CACHE/repos"
+ECOS_CACHE="$ECOS_HOME/cache"
+ECOS_INITIALIZED="$ECOS_CACHE/initialized"
+ECOS_CACHE_REPO_ECOS="$ECOS_CACHE/repos/ecos"
+ECOS_CACHE_TWEAKS="$ECOS_CACHE/tweaks"
 ECOS_SHOW_CHANGELOG="$ECOS_CACHE/show_changelog"
 ECOS_ARCH_ISO_FILE="$ECOS_CACHE/archlinux-x86_64.iso"
 ECOS_DESKTOP_FILE="$HOME/.local/share/applications/$SCRIPT_ID.desktop"
@@ -132,7 +116,7 @@ main() {
         if [ ! -f "$ECOS_INITIALIZED" ]; then
             tui_menu_init
         else
-            exit 0
+            exit
         fi
     fi
 
@@ -149,15 +133,15 @@ main() {
     # ---------------------------------------
     if [ "$1" = "--update-core" ]; then
         ecos_update_core
-        exit 0
+        exit
     fi
 
     # ---------------------------------------
     # UPDATE ECOS
     # ---------------------------------------
-    if [ "$1" = "--update" ]; then
+    if [ "$1" = "--update-system" ]; then
         ecos_update_system
-        exit 0
+        exit
     fi
 
     # ---------------------------------------
@@ -169,15 +153,7 @@ main() {
             whiptail --title "Changelog" --scrolltext --msgbox "$(cat "$SCRIPT_TUI_FILE")\n\n$SCRIPT_CHANGELOG" $SCRIPT_TUI_HEIGHT $SCRIPT_TUI_WIDTH 3>&1 1>&2 2>&3
             rm -f "$ECOS_SHOW_CHANGELOG"
         fi
-        exit 0
-    fi
-
-    # ---------------------------------------
-    # MANAGER
-    # ---------------------------------------
-    if [ "$1" = "--manager" ]; then
-        tui_menu_manager
-        exit 0
+        exit
     fi
 
     # ---------------------------------------
@@ -185,7 +161,7 @@ main() {
     # ---------------------------------------
     if [ "$1" = "--core" ]; then
         tui_menu_core_install
-        exit 0
+        exit
     fi
 
     #----------------------------------------
@@ -196,7 +172,11 @@ main() {
         if [ "$(cat /proc/sys/kernel/hostname)" = "archiso" ]; then
             tui_menu_core_install
         else
-            tui_menu_manager
+            if [ ! -f "$ECOS_INITIALIZED" ]; then
+                tui_menu_init
+            else
+                tui_menu_manager
+            fi
         fi
     fi
 }
@@ -295,7 +275,7 @@ tui_menu_manager() {
     #----------------------------------------
     if [ "$menu_input" = "0" ]; then
         ecos_update_core
-        "$ECOS_CORE" --update
+        "$ECOS_CORE" --update-system
         exit 0
     fi
 
@@ -1304,13 +1284,15 @@ ecos_tui_install_ecos() {
     exit 0
 }
 
+#/////////////////////////////////////////////////////
+# TWEAKS
+#/////////////////////////////////////////////////////
+
 ecos_tui_menu_tweaks() {
 
     ecos_check_git
     ecos_check_paru
 
-    local ecos_repo="$ECOS_LOCAL_REPOS_DIR/ecos"
-    local ecos_tweaks="$ecos_repo/tweaks"
     local tweaks_array_all=()
     local tweaks_array_enabled=()
     local tweaks_array_disabled=()
@@ -1319,25 +1301,26 @@ ecos_tui_menu_tweaks() {
     #----------------------------------------
     # UPDATE TWEAKS REPO
     #----------------------------------------
-    if ! [ -d "$ecos_repo" ]; then
+    if ! [ -d "$ECOS_CACHE_REPO_ECOS" ]; then
         print_title "Cloning Tweaks"
-        git clone "$ECOS_GIT_URL" "$ecos_repo"
+        git clone "$ECOS_GIT_URL" "$ECOS_CACHE_REPO_ECOS"
     fi
 
     print_title "Updating Tweaks..."
-    cd "$ecos_repo" || exit 1
+    cd "$ECOS_CACHE_REPO_ECOS" || exit 1
     git fetch --all
     git reset --hard origin/HEAD
 
     #----------------------------------------
     # READ TWEAK LIST
     #----------------------------------------
-    readarray -d '' tweak_dir_list < <(find "$ecos_tweaks" -mindepth 1 -maxdepth 1 -type d -print0)
+    readarray -d '' tweak_dir_list < <(find "$ECOS_CACHE_REPO_ECOS/tweaks" -mindepth 1 -maxdepth 1 -type d -print0)
 
     for i in "${tweak_dir_list[@]}"; do
 
         local tweak_id="$(basename $i)"
-        local tweak_sh="$ecos_tweaks/$tweak_id/$tweak_id.sh"
+        local tweak_sh="$ECOS_CACHE_REPO_ECOS/tweaks/$tweak_id/${tweak_id}.sh"
+        local tweak_meta="$ECOS_CACHE_TWEAKS/$tweak_id/${tweak_id}.tweak"
 
         # Check sh file
         if ! [ -f "$tweak_sh" ]; then
@@ -1345,7 +1328,7 @@ ecos_tui_menu_tweaks() {
         fi
 
         # Check if installed
-        if [ -f "$ECOS_CACHE/tweaks/$tweak_id/${tweak_id}.tweak" ]; then
+        if [ -f "$tweak_meta" ]; then
             # Add to enabled
             tweaks_array_enabled+=("$tweak_id")
         else
@@ -1414,7 +1397,7 @@ ecos_tui_menu_tweaks() {
     # EXECUTE TWEAK LIST
     #----------------------------------------
     for i in "${selected_array[@]}"; do
-        ecos_exec_tweak "$i" "$tweak_action_input"
+        ecos_exec_tweak "$tweak_action_input" "$i"
         wait
     done
 
@@ -1424,22 +1407,23 @@ ecos_tui_menu_tweaks() {
 
 ecos_exec_tweak() {
 
-    local tweak_id="$1"
-    local tweak_action="$2"
-    local tweak_res_dir="$ECOS_LOCAL_REPOS_DIR/ecos/tweaks/$tweak_id"
-    local tweak_cache_dir="$ECOS_CACHE/tweaks/$tweak_id"
-    local tweak_sh="$tweak_res_dir/$tweak_id.sh"
+    local tweak_action="$1"
+    local tweak_id="$2"
+    local tweak_res_dir="$ECOS_CACHE_REPO_ECOS/tweaks/$tweak_id"
+    local tweak_cache_dir="$ECOS_CACHE_TWEAKS/$tweak_id"
+    local tweak_sh="$tweak_res_dir/${tweak_id}.sh"
+    local tweak_meta="$tweak_cache_dir/${tweak_id}.tweak"
 
     #----------------------------------------
     # Check
     #----------------------------------------
     if [ "$tweak_id" = "" ]; then
-        echo -e "Error: Tweak ID is empty.\nExecute with:\n$ECOS_CORE --tweak TWEAK_ID TWEAK_ACTION"
+        echo -e "Error: Tweak ID is empty.\nExecute with:\n$ECOS_CORE --tweak TWEAK_ACTION TWEAK_ID"
         exit 1
     fi
 
     if [ "$tweak_action" = "" ]; then
-        echo -e "Error: TWEAK_ACTION is empty.\nExecute with:\n$ECOS_CORE --tweak TWEAK_ID TWEAK_ACTION"
+        echo -e "Error: TWEAK_ACTION is empty.\nExecute with:\n$ECOS_CORE --tweak TWEAK_ACTION TWEAK_ID"
         exit 1
     fi
 
@@ -1462,7 +1446,7 @@ ecos_exec_tweak() {
 
         # Install or update
         if [ "$tweak_action" = "install" ] || [ "$tweak_action" = "update" ]; then
-            echo "$(date "+%Y-%m-%d-%H:%M:%S")" >"$tweak_cache_dir/$tweak_id.tweak"
+            echo "$(date "+%Y-%m-%d-%H:%M:%S")" >"$tweak_meta"
         fi
 
         # Remove
@@ -1474,6 +1458,20 @@ ecos_exec_tweak() {
     fi
 }
 
+ecos_update_tweaks() {
+    local tweak_dir_list=()
+    readarray -d '' tweak_dir_list < <(find "$ECOS_CACHE_TWEAKS" -mindepth 1 -maxdepth 1 -type d -print0)
+    for i in "${tweak_dir_list[@]}"; do
+        local tweak_id="$(basename $i)"
+        local tweak_sh="$ECOS_CACHE_REPO_ECOS/$tweak_id/${tweak_id}.sh"
+        ecos_exec_tweak "update" "$tweak_id"
+    done
+}
+
+#/////////////////////////////////////////////////////
+# UPDATE
+#/////////////////////////////////////////////////////
+
 ecos_update_core() {
 
     check_internet
@@ -1482,7 +1480,7 @@ ecos_update_core() {
     mkdir -p "$ECOS_HOME"
     mkdir -p "$ECOS_CACHE"
     mkdir -p "$ECOS_BIN_DIR"
-    mkdir -p "$ECOS_LOCAL_REPOS_DIR"
+    mkdir -p "$ECOS_CACHE_REPO_ECOS"
     mkdir -p "$HOME/.local/share/applications"
 
     local tmp_ecos="$ECOS_CACHE/ecos-new"
@@ -1557,6 +1555,11 @@ ecos_update_system() {
             bash -c "$ECOS_INIT --update"
         fi
     fi
+
+    # UPDATE TWEAKS
+    print_title 'UPDATING ECOS TWEAKS'
+    ecos_update_tweaks
+
     # UPDATE DESKTOP FILE
     print_title 'UPDATING ECOS DESKTOP FILE'
     mkdir -p "$HOME/.local/share/applications/"
