install

diff --git a/ecos b/ecos
--- a/ecos
+++ b/ecos
@@ -1284,7 +1284,23 @@ open_tui_install_ecos() {
     print_header
 
     print_title "INSTALL ECOS CORE"
-    update_core_installation
+    mkdir -p "$ECOS_BIN"
+    mkdir -p "$ECOS_CACHE/update"
+    local tmp_ecos="$ECOS_CACHE/update/ecos"
+    if ! curl -s -L "$ECOS_CORE_URL" >"$tmp_ecos"; then
+        echo "ERROR: ECOS CORE DOWNLOAD"
+        exit 1
+    fi
+    if [ ! -f "$tmp_ecos" ]; then
+        echo "ERROR: ECOS UPDATE FILE NOT FOUND"
+        exit 1
+    else
+        mv "$tmp_ecos" "$ECOS_CORE"
+    fi
+    if ! chmod +x "$ECOS_CORE"; then
+        echo "ERROR: ECOS CORE NOT FOUND"
+        exit 1
+    fi
 
     print_title "CHECK GIT"
     check_git
