ECOS RELEASE 2.1.8

diff --git a/release/ecos b/release/ecos
--- a/release/ecos
+++ b/release/ecos
@@ -1,5 +1,5 @@
 #!/bin/bash
-SCRIPT_VERSION=2.1.7
+SCRIPT_VERSION=2.1.8
 
 #/////////////////////////////////////////////////////
 # SCRIPT VARIABLES
@@ -118,6 +118,14 @@ set_lang_de_DE() {
 
 main() {
 
+    #----------------------------------------
+    # CHROOT MODE
+    #----------------------------------------
+    if [ "$1" = "--install-chroot" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
+        core_install_chroot "$2" "$3"
+        exit $?
+    fi
+
     # ---------------------------------------
     # VERSION
     # ---------------------------------------
@@ -140,14 +148,6 @@ main() {
     if [ "$1" = "--install-core" ]; then
         tui_menu_install_core
         exit 0
-    fi
-
-    #----------------------------------------
-    # CHROOT MODE
-    #----------------------------------------
-    if [ "$1" = "--install-chroot" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
-        core_install_chroot "$2" "$3"
-        exit $?
     fi
 
     # ---------------------------------------
@@ -457,8 +457,7 @@ tui_menu_manager() {
     # Update ECOS
     #----------------------------------------
     if [ "$menu_input" = "1" ]; then
-        ecos_update_core
-        "$ECOS_CORE" --update-system
+        ecos_update_system
         exit 0
     fi
 
@@ -1456,16 +1455,20 @@ ecos_tui_install_ecos() {
     clear
     print_header
 
-    print_title "INSTALL ECOS CORE"
-    ecos_update_core
-    echo -e "DONE"
-
     print_title "CHECK GIT"
     ecos_check_git
     echo -e "DONE"
 
     print_title "CHECK PARU"
     ecos_check_paru
+    echo -e "DONE"
+
+    print_title "INSTALL ECOS CORE"
+    ecos_update_core
+    echo -e "DONE"
+
+    print_title "INSTALL ECOS REPO"
+    ecos_update_repo
     echo -e "DONE"
 
     print_title "CLONE DOTFILES"
@@ -1496,7 +1499,9 @@ ecos_tui_install_ecos() {
 
     # Call init script
     echo -e "EXECUTE $ECOS_INIT_SCRIPT"
-    chmod +x "$ECOS_INIT_SCRIPT" && "$ECOS_INIT_SCRIPT" --install
+    chmod +x "$ECOS_INIT_SCRIPT" || exit 1
+    "$ECOS_INIT_SCRIPT" --init
+    "$ECOS_INIT_SCRIPT" --update
 
     # Create dots bin
     local dots_bin="$ECOS_BIN_DIR/dots"
@@ -1532,18 +1537,59 @@ ecos_tui_install_ecos() {
 # UPDATE
 #/////////////////////////////////////////////////////
 
-ecos_update_cache_repo() {
+ecos_update_core() {
+
+    check_internet
+    ecos_init_dirs
+
+    local ecos_update="$ECOS_WORKING_DIR/ecos.upate"
+    if ! curl -s -L "$ECOS_CORE_RELEASE_URL" >"$ecos_update"; then
+        echo "ERROR: ECOS CORE UPDATE DOWNLOAD: $ECOS_CORE_RELEASE_URL"
+        exit 1
+    fi
+    if [ ! -f "$ecos_update" ]; then
+        echo "ERROR: ECOS CORE UPDATE NOT FOUND: $ecos_update"
+        exit 1
+    else
+        if ! chmod +x "$ecos_update"; then
+            echo "ERROR: CHMOD CORE UPDATE: $ecos_update"
+            exit 1
+        fi
+        local ecos_current_version="$($ECOS_CORE --version)"
+        local ecos_update_version="$($ecos_update --version)"
+        if [ "$ecos_current_version" != "$ecos_update_version" ]; then
+            if ! mv "$ecos_update" "$ECOS_CORE"; then
+                echo "ERROR: MOVE CORE: $ecos_update --> $ECOS_CORE"
+                exit 1
+            fi
+            if ! chmod +x "$ECOS_CORE"; then
+                echo "ERROR: CHMOD CORE: $ECOS_CORE"
+                exit 1
+            fi
+            echo "NEW ECOS CORE UPDATE: $ecos_current_version --> $ecos_update_version"
+        else
+            rm -f "$ecos_update_version"
+            echo "$SCRIPT_TITLE $($ECOS_CORE --version): NO CORE UPDATE AVAILABLE (REMOTE: $ecos_update_version)"
+        fi
+    fi
+}
+
+ecos_update_repo() {
+
+    ecos_init_dirs
 
     if ! [ -d "$ECOS_REPO/.git" ]; then
+        echo "CLONE ECOS REPO"
         mkdir -p "$ECOS_REPO"
         git clone "$ECOS_REPO_URL" "$ECOS_REPO"
     fi
 
     if ! [ -d "$ECOS_REPO/.git" ]; then
-        echo "Error: Cant find $ECOS_REPO/.git"
+        echo "ERROR CLONE ECOS REPO: Cant find $ECOS_REPO/.git"
         exit 1
     fi
 
+    echo "UPDATE ECOS REPO"
     cd "$ECOS_REPO" || exit 1
     git fetch --all
     git reset --hard origin/HEAD
@@ -1571,42 +1617,6 @@ ecos_update_cache_repo() {
     fi
 }
 
-ecos_update_core() {
-
-    check_internet
-    ecos_init_dirs
-
-    local ecos_update="$ECOS_WORKING_DIR/ecos.upate"
-    if ! curl -s -L "$ECOS_CORE_RELEASE_URL" >"$ecos_update"; then
-        echo "ERROR: ECOS CORE UPDATE DOWNLOAD: $ECOS_CORE_RELEASE_URL"
-        exit 1
-    fi
-    if [ ! -f "$ecos_update" ]; then
-        echo "ERROR: ECOS CORE UPDATE NOT FOUND: $ecos_update"
-        exit 1
-    else
-        if ! chmod +x "$ecos_update"; then
-            echo "ERROR: CHMOD CORE UPDATE: $ecos_update"
-            exit 1
-        fi
-        local ecos_current_version="$($ECOS_CORE --version)"
-        local ecos_update_version="$($ecos_update --version)"
-        if [ "$ecos_current_version" != "$ecos_update_version" ]; then
-            if ! mv "$ecos_update" "$ECOS_CORE"; then
-                echo "ERROR: MOVE CORE: $ecos_update ---> $ECOS_CORE"
-                exit 1
-            fi
-            if ! chmod +x "$ECOS_CORE"; then
-                echo "ERROR: CHMOD CORE: $ECOS_CORE"
-                exit 1
-            fi
-            echo "NEW ECOS CORE UPDATE: $ecos_current_version ---> $ecos_update_version"
-        else
-            echo "$SCRIPT_TITLE $($ECOS_CORE --version): NO CORE UPDATE AVAILABLE (REMOTE: $ecos_update_version)"
-        fi
-    fi
-}
-
 ecos_update_system() {
 
     clear
@@ -1616,70 +1626,90 @@ ecos_update_system() {
     print_title 'CHECK ECOS DEPENDENCIES'
     ecos_check_git
     ecos_check_paru
+    ecos_check_zenity
+    echo ">>> OK"
+
+    print_title 'UPDATE ECOS CORE'
+    ecos_update_core
     echo ">>> OK"
 
     print_title 'UPDATE ECOS REPO'
-    ecos_update_cache_repo
+    ecos_update_repo
+    echo ">>> OK"
+
+    # PACKAGE UPDATE
+    print_title 'FETCH NEW PACKAGES'
+    paru -Syy
+
+    echo -e '\n'
+    read -p "Continue ECOS System Upgrade? [y/n]: " user_input
+    if [ "$user_input" != "y" ]; then
+        echo "Skipped..."
+        exit 0
+    fi
+
+    # PACKAGE UPGRADE
+    echo -e '\n'
+    print_title 'UPGRADE NEW PACKAGES'
+    paru -Qu
+    if ! paru -Su --noconfirm; then
+        echo -e "ERROR: paru"
+        exit 1
+    fi
+    wait
     echo ">>> OK"
 
     # DOTFILES UPDATE
     print_title 'ECOS DOTFILES UPDATE'
     cd "$HOME" || exit 1
 
+    # CURRENT INIT VERSION
+    local current_init_script_version=''
+    if [ -f "$ECOS_INIT_SCRIPT" ]; then
+        current_init_script_version="$($ECOS_INIT_SCRIPT --version)"
+    fi
+
     # RESET LOCAL FILES
     git --git-dir="$ECOS_DOTFILES" --work-tree="$HOME" fetch --all
     git --git-dir="$ECOS_DOTFILES" --work-tree="$HOME" reset --hard HEAD
     git --git-dir="$ECOS_DOTFILES" --work-tree="$HOME" pull
-
-    # PACKAGE UPDATE
-    print_title 'FETCH PACKAGE UPDATES'
-    paru -Syy
-
-    # PACKAGE UPGRADE
-    print_title 'UPGRADE SYSTEM PACKAGES'
-    paru -Qu
-    echo ''
-    read -p "Upgrade packages? [y/n]: " user_input
-    if [ "$user_input" = "y" ]; then
-        if ! paru -Su --noconfirm; then
-            echo -e "ERROR: paru"
-            exit 1
-        fi
-        wait
-
-    else
-        echo "Skipped..."
-    fi
+    echo ">>> OK"
 
     # UPDATE TWEAKS
-    print_title 'UPDATING ECOS TWEAKS'
+    print_title 'UPDATE ECOS TWEAKS'
     ecos_update_tweaks
+    echo ">>> OK"
 
     # UPDATE INIT FILE
     if [ -f "$ECOS_INIT_SCRIPT" ]; then
-        latest_changelog_version=""
+
+        # Check initialized version
+        local ecos_initialized_version=""
         if [ -f "$ECOS_STATE_INITIALIZED" ]; then
-            latest_changelog_version=$(<"$ECOS_STATE_INITIALIZED")
+            ecos_initialized_version=$(<"$ECOS_STATE_INITIALIZED")
         fi
-        if [ "$SCRIPT_VERSION" != "$latest_changelog_version" ]; then
-            print_title 'REINSTALL ECOS INIT FILE'
-            "$ECOS_INIT_SCRIPT" --install
+
+        # Update if initialized file not exists or new init script available
+        local new_init_script_version="$($ECOS_INIT_SCRIPT --version)"
+        if [ "$SCRIPT_VERSION" != "$ecos_initialized_version" ] || [ "$new_init_script_version" != "$current_init_script_version" ]; then
+            echo "UPDATE INIT SCRIPT"
+            "$ECOS_INIT_SCRIPT" --update
             echo "$SCRIPT_VERSION" >"$ECOS_STATE_INITIALIZED"
             touch "$ECOS_STATE_SHOW_CHANGELOG"
+            echo ">>> OK"
         else
-            print_title 'UPDATING ECOS INIT FILE'
-            "$ECOS_INIT_SCRIPT" --update
+            echo "INIT UPDATE SKIPPED..."
+            echo ">>> OK"
         fi
     fi
 
     # UPDATE DESKTOP FILE
-    print_title 'UPDATE ECOS FILES'
-    # Create desktop file
+    print_title 'UPDATE ECOS DESKTOP FILE'
     ecos_create_desktop_file
     echo ">>> OK"
 
     # FINISH
-    print_title 'ECOS UPDATE FINISHED'
+    print_title '!! ECOS UPDATE FINISHED !!'
     echo ""
     read -p "Press any Key to close..."
     exit 0
@@ -1693,10 +1723,6 @@ ecos_tui_menu_tweaks() {
 
     ecos_check_git
     ecos_check_paru
-
-    if [ "$1" != '--no-update' ]; then
-        ecos_update_cache_repo
-    fi
 
     local tweaks_array_all=()
     local tweaks_array_enabled=()
@@ -1810,11 +1836,6 @@ ecos_exec_tweak() {
     local tweak_meta="$tweak_cache_dir/${tweak_id}.tweak"
 
     #----------------------------------------
-    # Check & update repo
-    #----------------------------------------
-    ecos_update_cache_repo
-
-    #----------------------------------------
     # Check
     #----------------------------------------
     if [ "$tweak_id" = "" ]; then
@@ -1869,7 +1890,6 @@ ecos_exec_tweak() {
 
 ecos_update_tweaks() {
     local tweak_dir_list=()
-    ecos_update_cache_repo
     readarray -d '' tweak_dir_list < <(find "$ECOS_CACHE_TWEAKS" -mindepth 1 -maxdepth 1 -type d -print0)
     for i in "${tweak_dir_list[@]}"; do
         local tweak_id="$(basename $i)"
