ECOS RELEASE 2.1.5

diff --git a/release/ecos b/release/ecos
--- a/release/ecos
+++ b/release/ecos
@@ -1,5 +1,5 @@
 #!/bin/bash
-SCRIPT_VERSION=2.1.4
+SCRIPT_VERSION=2.1.5
 
 #/////////////////////////////////////////////////////
 # SCRIPT VARIABLES
@@ -18,6 +18,10 @@ SCRIPT_TUI_HEIGHT=24
 #/////////////////////////////////////////////////////
 
 COLOR_RED='\033[0;31m'
+COLOR_GREEN='\033[1;32m'
+COLOR_BLUE='\033[1;34m'
+COLOR_PURPLE='\033[1;35m'
+COLOR_YELLOW='\033[1;33m'
 COLOR_NULL='\033[0m' # No Color
 
 #/////////////////////////////////////////////////////
@@ -280,7 +284,7 @@ zenity_manager() {
     if [ "$ECOS_REMOTE_VERSION" = '' ]; then
 
         (
-            if ! ecos_init_ecos; then
+            if ! ecos_init_ecos && ecos_update_repo; then
                 echo "CANCELED" >"$pid_file"
             else
                 echo "SUCCESS" >"$pid_file"
@@ -1510,30 +1514,28 @@ ecos_init_ecos() {
 
     # SET REMOTE ECOS VERSION
     if [ "$ECOS_REMOTE_VERSION" = '' ]; then
-        echo "DOWNLOAD REMOTE ECOS"
         local ecos_update="$ECOS_REMOTE_VERSION_FILE"
 
         if ! curl -s -L "$ECOS_CORE_RELEASE_URL" >"$ECOS_REMOTE_VERSION_FILE"; then
-            echo "ERROR: ECOS DOWNLOAD: $ECOS_CORE_RELEASE_URL"
+            echo "ERROR: DOWNLOAD ECOS: $ECOS_CORE_RELEASE_URL"
             return 1
         fi
         if ! chmod +x "$ECOS_REMOTE_VERSION_FILE"; then
-            echo "ERROR: CHMOD: $ECOS_REMOTE_VERSION_FILE"
+            echo "ERROR: CHMOD ECOS: $ECOS_REMOTE_VERSION_FILE"
             return 1
         fi
 
         ECOS_REMOTE_VERSION="$($ECOS_REMOTE_VERSION_FILE --version)"
-        echo "ECOS_REMOTE_VERSION=$ECOS_REMOTE_VERSION"
+        echo "ECOS LOCAL VERSION:   $SCRIPT_VERSION"
+        echo "ECOS REMOTE VERSION:  $ECOS_REMOTE_VERSION"
     fi
-
-    # UPDATE REPO
-    ecos_update_repo
 }
 
 ecos_tui_install_ecos() {
 
     check_internet
     ecos_init_ecos
+    ecos_update_repo
 
     tui_init 0 "Dotfiles URL"
     if ! ECOS_DOTS_DEFAULT_URL=$(whiptail --inputbox "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" "$ECOS_DOTS_DEFAULT_URL" 3>&1 1>&2 2>&3); then
@@ -1669,7 +1671,6 @@ ecos_update_core() {
             touch "$ECOS_STATE_SHOW_CHANGELOG"
         else
             rm -f "$ecos_update"
-            echo "$SCRIPT_TITLE CORE $($ECOS_CORE --version) UP TO DATE"
         fi
     fi
 }
@@ -1723,7 +1724,7 @@ ecos_update_system() {
     ecos_check_zenity
     echo ">>> OK"
 
-    print_title 'UPDATE ECOS CORE'
+    print_title 'INIT ECOS CORE'
     ecos_update_core
     echo ">>> OK"
 
@@ -1731,29 +1732,26 @@ ecos_update_system() {
     ecos_update_repo
     echo ">>> OK"
 
-    # PACKAGE UPDATE
-    print_title 'FETCH NEW PACKAGES'
-    echo -e '\n'
+    # FETCH PACKAGES
+    print_title 'FETCH PACMAN/AUR PACKAGES'
     paru -Syy
     echo ">>> OK"
 
     # LIST PACKAGES
-    echo -e '\n'
-    echo -e '------------------------------------------'
+    print_title 'FETCH PACMAN/AUR PACKAGES'
     if ! paru -Qu; then
-        echo -e 'No Package Updates available'
+        echo -e '>>> No Package Updates available'
     fi
-    echo -e '------------------------------------------'
-    echo -e '\n'
 
-    read -p "Continue ECOS System Upgrade? [y/n]: " user_input
+    print_title 'ECOS SYSTEM UPGRADE'
+    read -p "Continue? [y/n]: " user_input
     if [ "$user_input" != "y" ]; then
-        echo "Skipped..."
+        echo ">>> Skipped..."
         exit 0
     fi
 
     # PACKAGE UPGRADE
-    print_title 'UPGRADE NEW PACKAGES'
+    print_title 'UPADE PACMAN/AUR PACKAGES'
     if ! paru -Su --noconfirm; then
         echo -e "ERROR: paru"
         exit 1
@@ -1762,7 +1760,7 @@ ecos_update_system() {
     echo ">>> OK"
 
     # DOTFILES UPDATE
-    print_title 'ECOS DOTFILES UPDATE'
+    print_title 'UPDATE ECOS DOTFILES'
     cd "$HOME" || exit 1
 
     # RESET LOCAL FILES
@@ -1772,7 +1770,7 @@ ecos_update_system() {
     echo ">>> OK"
 
     # UPDATE INIT FILE
-    print_title "DOTFILE INIT SCRIPT"
+    print_title "EXECUTE INIT SCRIPT"
     if [ -f "$ECOS_INIT_SCRIPT" ]; then
 
         local current_init_version="$($ECOS_INIT_SCRIPT --version)"
@@ -1791,7 +1789,6 @@ ecos_update_system() {
                 echo -e "USER SKIPPED..."
                 echo ">>> OK"
             else
-                echo "EXECUTE INIT SCRIPT"
                 "$ECOS_INIT_SCRIPT" --init
                 echo "$($ECOS_INIT_SCRIPT --version)" >"$ECOS_STATE_LATEST_INIT"
                 echo ">>> OK"
@@ -1818,7 +1815,7 @@ ecos_update_system() {
     echo ">>> OK"
 
     # FINISH
-    print_title '!! ECOS UPDATE FINISHED !!'
+    print_title "${COLOR_GREEN} !! ECOS UPDATE FINISHED !! ${COLOR_NULL}"
     echo ""
     read -p "Press any Key to close..."
     exit 0
@@ -1889,7 +1886,7 @@ ecos_tui_menu_tweaks() {
         selected_tweaks_array=("${tweaks_array_disabled[@]}")
     fi
     if [ "$tweak_action_input" = "update" ]; then
-        tweak_status='on'
+        tweak_status='off'
         selected_tweaks_array=("${tweaks_array_enabled[@]}")
     fi
     if [ "$tweak_action_input" = "remove" ]; then
@@ -1960,7 +1957,7 @@ ecos_exec_tweak() {
     # Execute Tweak
     #----------------------------------------
     if [ "$tweak_action" = "install" ] || [ "$tweak_action" = "remove" ] || [ "$tweak_action" = "update" ]; then
-        print_title "TWEAK | $tweak_action: $tweak_id"
+        print_title "${COLOR_YELLOW}TWEAK: $tweak_id ($tweak_action)${COLOR_NULL}"
         if ! [ -f "$tweak_sh" ]; then
             echo "Error: $tweak_id not exists ($tweak_sh)"
             return 1
@@ -1978,18 +1975,18 @@ ecos_exec_tweak() {
             # Install or update on success
             if [ "$tweak_action" = "install" ] || [ "$tweak_action" = "update" ]; then
                 echo "$(date "+%Y-%m-%d-%H:%M:%S")" >"$tweak_meta"
-                echo -e "\nTWEAK $tweak_id:  Successfully installed/updated\n"
+                echo -e "Successfully installed/updated"
             fi
 
             # Remove on success
             if [ "$tweak_action" = "remove" ]; then
                 rm -rf "$tweak_cache_dir"
-                echo -e "\nTWEAK $tweak_id:  Successfully removed\n"
+                echo -e "Successfully removed"
             fi
         else
             # Remove dir if error during execution
             rm -rf "$tweak_cache_dir"
-            echo -e "\nTWEAK $tweak_id: Failed\n"
+            echo -e "Failed"
         fi
     else
         echo "Error: TWEAK_ACTION=$tweak_action not supported"
@@ -2205,21 +2202,22 @@ tui_add() {
 }
 
 print_header() {
-    echo '
-    ███████╗ ██████╗ ██████╗ ███████╗
-    ██╔════╝██╔════╝██╔═══██╗██╔════╝
-    █████╗  ██║     ██║   ██║███████╗
-    ██╔══╝  ██║     ██║   ██║╚════██║
-    ███████╗╚██████╗╚██████╔╝███████║
-    ╚══════╝ ╚═════╝ ╚═════╝ ╚══════╝
-                              v.'$SCRIPT_VERSION''
+    echo -e "
+        ${COLOR_GREEN}
+        ███████╗ ██████╗ ██████╗ ███████╗
+        ██╔════╝██╔════╝██╔═══██╗██╔════╝
+        █████╗  ██║     ██║   ██║███████╗
+        ██╔══╝  ██║     ██║   ██║╚════██║
+        ███████╗╚██████╗╚██████╔╝███████║
+        ╚══════╝ ╚═════╝ ╚═════╝ ╚══════╝${COLOR_NULL}
+                                  ${COLOR_YELLOW}v.${SCRIPT_VERSION}${COLOR_NULL}"
 }
 
 print_title() {
     echo -e "\n"
-    echo -e ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
-    echo -e "> $1"
-    echo -e ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
+    echo -e "${COLOR_BLUE}>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>${COLOR_NULL}"
+    echo -e "${COLOR_BLUE}>>>${COLOR_NULL}  ${COLOR_PURPLE}${1}${COLOR_NULL}"
+    echo -e "${COLOR_BLUE}>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>${COLOR_NULL}"
 }
 
 check_internet() {
